### ISSUE TITLE
ILCSoft does not work anymore in zsh

### ISSUE THREAD

**Issue by ueinhaus** [iLCSoft/iLCInstall#142] opened 2021-03-12 17:57 UTC
To make it short, using zsh gives an error when init_ilsoft.sh is sourced.
This is true since v02-01, while v02-00-02 was still working.
Presumably  this is due to ENV variables in DD4HEP (that changed from v01-07-02 to v01-11-02), which are in conflict with default ones in zsh.
This is not only forcing me right now to use bash for the moment, but it also came without warning or proper error message, leading to repeated  frustration over "Why does this not work anymore??".

**Comment by tmadlener** [comment] 2022-02-15 09:15
This is indeed a problem of DD4hep, that was introduced somewhere between v01-07-02 and v01-11-02 (of DD4hep). The problem is L58 here: https://github.com/AIDASoft/DD4hep/blob/2d88cf58bf4644b4cce292f24f746ced4d4881ba/cmake/thisdd4hep.sh#L58-L61

Starting with v01-13 of DD4hep everything should work again (L59-61 above).

**Comment by tmadlener** [comment] 2022-12-06 16:06
Closing this, as it is a DD4hep issue and fixed again with newer versions of DD4hep.

**Closed by tmadlener** 2022-12-06 16:06 UTC
